{{- if and .Values.clickhouse.password (not .Values.clickhouse.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-ch" (include "spangen.fullname" .) }}
  labels:
    {{- include "spangen.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.clickhouse.passwordKey }}: {{ .Values.clickhouse.password | quote }}
{{- end }}
